version: "3"

services:
  postgres:
    build:
      context: .
      dockerfile: postgres-dockerfile
    environment:
      TZ: IST
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # POSTGRES_HOST: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  scheduler:
    build: 
      context: .
      dockerfile: scheduler-dockerfile
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: postgres
      VITE_WEB_API: "localhost:8081/api"
    ports:
      - "8081:8081"
    depends_on:
      - postgres

  coordinator:
    build:
      context: .
      dockerfile: coordinator-dockerfile
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: postgres
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  worker-1:
    build:
      context: .
      dockerfile: worker-dockerfile
    ports:
      - "8100:8082"
    environment:
      WORKER_ADDRESS: worker-1
      VITE_WEB_API: "localhost:8100/api"
    depends_on:
      - coordinator


  worker-2:
    build:
      context: .
      dockerfile: worker-dockerfile
    ports:
      - "8101:8082"
    environment:
      WORKER_ADDRESS: worker-2
      VITE_WEB_API: "localhost:8101/api"
    depends_on:
      - coordinator